// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce.Models;

[Table("Cart")]
public partial class Cart
{
    [Key]
    public int id { get; set; }

    public int userid { get; set; }

    public int productid { get; set; }

    public int count { get; set; }

    [ForeignKey("productid")]
    [InverseProperty("Carts")]
    public virtual Product product { get; set; }
}