// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce.Models;

[Table("Review")]
public partial class Review
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(255)]
    public string name { get; set; }

    [Required]
    [StringLength(50)]
    public string email { get; set; }

    [StringLength(255)]
    public string subject { get; set; }

    [Column(TypeName = "text")]
    public string description { get; set; }
}